### ISSUE TITLE
Close bug report pop-up.

### ISSUE THREAD

**Issue by s-moffatt** [cognitive-engineering-lab/mdbook-quiz#15]
- [ ] I have checked the latest `main` branch to see if this has already been fixed
- [ ] I have searched existing issues and pull requests for duplicates

URL to the section(s) of the book with this problem:

Description of the problem:
It took me a few seconds to figure out how to close the bug report pop-up. It's not obvious that I need to click the bug icon again to close the pop-up box.

Suggested fix:
Other websites I've seen allow the user to click anywhere outside of a pop-up to cancel it. Or have a close (X) button on the dialog itself.

**Comment by willcrichton** [comment]
Thanks for the report @s-moffatt. I will add a separate button to close the report window in the next mdbook-quiz release.
