### ISSUE TITLE
Code snippets in prompt get cut off by bottom edge

### ISSUE THREAD

**Issue by westluke** [cognitive-engineering-lab/mdbook-quiz#21]
It looks like if the question prompt ends in a code snippet, the bottom of the last line can get cut short. I've noticed this at several zoom levels, although it is most prominent at <100% zoom. I'm using Firefox version 112.0.2 on Linux. This is mostly a cosmetic issue, although when severe enough it can cause underscores on the last line to disappear entirely; see the attached photos.

![Screenshot from 2023-05-12 15-04-44](https://github.com/cognitive-engineering-lab/mdbook-quiz/assets/7086426/4e8ce6ab-15de-4096-b026-cc8c674dcfdc)
![Screenshot from 2023-05-12 15-04-16](https://github.com/cognitive-engineering-lab/mdbook-quiz/assets/7086426/03de1afa-08aa-48d8-98ab-a2b5e39a8a89)
![Screenshot from 2023-05-12 15-00-46](https://github.com/cognitive-engineering-lab/mdbook-quiz/assets/7086426/ccd82221-aba2-44bf-8b8a-ae769a16d860)
![Screenshot from 2023-05-12 14-59-14](https://github.com/cognitive-engineering-lab/mdbook-quiz/assets/7086426/7789b0a4-1d8e-4746-aadb-ff46213dd2d8)

**Comment by willcrichton** [comment]
Sorry for the delay @westluke. The release v0.2.15 should fix this issue. Can you try the latest mdbook-quiz and confirm?

**Comment by willcrichton** [comment]
Ok I'm going to mark this as fixed, but please reopen if the issue reappears!
