### ISSUE TITLE
Is it possible to make quiz work in the generated static output?

### ISSUE THREAD

**Issue by saferust** [cognitive-engineering-lab/mdbook-quiz#37]
I have noticed that quizzes created with `mdbook-quiz` are displayed correctly when serving the `mdbook` locally using `mdbook serve`. However, when I generate static HTML files and access them from the `book/index.html` file, the quizzes do not render. 

Is there a workaround or specific configuration that would allow quizzes to be displayed and rendered correctly in the generated static HTML files?

**Comment by willcrichton** [comment]
I'm assuming you opened the file in your browser as a `file://` URL. That blocks loading the mdbook-quiz script, and you should see an error like this in the JS console:

```
index.html:1 Access to script at 'file:///[...]/rust-book/book/quiz/quiz-embed.mjs' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
```

I don't know of a way around that with a `file://` URL. But a simple workaround that doesn't depend on `mdbook serve` is to host a local server, such as by running this command in the `book` directory:

```
python3 -m http.server
```

**Comment by willcrichton** [comment]
I'm going to close this as fixed, please let me know if this doesn't work for you.
