### ISSUE TITLE
Duplicate Id error

### ISSUE THREAD

**Issue by amiyatulu** [cognitive-engineering-lab/mdbook-quiz#48]
× Duplicate ID: 7238e60d-2e38-4742-ac61-159746755e20   

But there are no duplicate ids.

Quiz failed to validate: file.toml                                                                         │
│2024-09-05 11:31:39 [ERROR] (mdbook::utils): Error: The "quiz" preprocessor exited unsuccessfully with exit status: 1 status

**Comment by willcrichton** [comment]
Oh are you embedding the same quiz in two different places or pages? That's a but then, we shouldn't mark those as duplicates.

**Comment by amiyatulu** [comment]
>Oh are you embedding the same quiz in two different places or pages? 

Yes.

**Comment by willcrichton** [comment]
This will be fixed in the next release!
